version: "2"
services:
  web:
    build:
       context: web
    environment:
      - SERVER_URL=localhost:8080
    volumes:
      - ./frontend/src:/server/src
    ports:
      - "3000:3000"
    networks:
      - onboarder
    depends_on:
      - backend
  backend:
    build:
      context: backend
    environment:
      - EMAIL=jade.e.hayes@gmail.com
      - WERKZEUG_DEBUG_PIN="off"
    volumes:
      - "./backend:/app"
    ports:
      - "8080:8080"
    networks:
      - onboarder

networks:
  onboarder:
