version: '2'
services:
  frontend:
    build:
       context: frontend
       dockerfile: Dockerfile
    environment:
      - SERVER_URL=localhost:8080
    volumes:
      - ./frontend/src:/server/src
    ports:
      - "3000:3000"
    networks:
      - web_nw
    depends_on:
      - backend
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - EMAIL=jade.e.hayes@gmail.com
      - WERKZEUG_DEBUG_PIN="off"
    volumes:
      - "./backend:/app"
    ports:
      - "8080:8080"
    networks:
      - web_nw
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    depends_on:
      - frontend
      - backend
    ports:
      - "443:8081"
    networks:
      - web_nw
networks:
    web_nw:
        driver: bridge
